### ISSUE TITLE
Custom properties dark mode

### ISSUE THREAD

**Issue by Stefan-Espant** [DamianR2004/look-and-feel-corporate-identity#1]
Top dat je gebruik maakt van custom properties om een dark mode toe te voegen aan je site. Check of je een semantische naamgeving kan verzinnen. Zo voorkom je dat wit zwart word en zwart wit word gedefineerd.

https://github.com/DamianR2004/look-and-feel-corporate-identity/blob/af94655a5aafd65a758b8cf15532cc0186c8c1a1/styles/style.css#L25-L40

**Comment by DamianR2004** [comment]
Gedaan, thanks!
