### ISSUE TITLE
Vergeet je koppeling niet met je label

### ISSUE THREAD

**Issue by Tolga1999** [DamianR2004/look-and-feel-corporate-identity#10]
https://github.com/DamianR2004/look-and-feel-corporate-identity/blob/6ba9ea5dcb7ab483955cd5f4f0a9d26fe5e67cb3/index.html#L394-L397

Vergeet je input niet te koppelen met je label, je mist een `name="naam"`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit

**Comment by DamianR2004** [comment]
Thanks! Is opgelost
