### ISSUE TITLE
Vereenvoudig je border gebruik

### ISSUE THREAD

**Issue by Stefan-Espant** [DamianR2004/look-and-feel-corporate-identity#4]
Je kan eventueel `border-bottom` gebruiken voor beide sections gebruiken. Zo voorkom je dat je meer code schrijft om vervolgens de instelling die je eerder hebt geschreven uitschakelt. Zo vereenvoudig je jouw code en schrijf je hiermee efficiënter CSS. 

https://github.com/DamianR2004/look-and-feel-corporate-identity/blob/3f7c71bab676466c89e46b4ed9dd10ff23cfec2e/styles/style.css#L248-L251

**Comment by DamianR2004** [comment]
Zojuist opgelost, thanks!
