### ISSUE TITLE
Annuleer button

### ISSUE THREAD

**Issue by Anna-Kyra** [DamianR2004/look-and-feel-corporate-identity#5]
<img width="401" alt="Scherm­afbeelding 2023-12-01 om 10 50 48" src="https://github.com/DamianR2004/look-and-feel-corporate-identity/assets/144000242/d899133a-030b-469d-9b75-1513dcbc221c">

De annuleer button werkt nog niet

**Comment by DamianR2004** [comment]
Opgelost, thanks!😁
