### ISSUE TITLE
h1 1 keer gebruiken

### ISSUE THREAD

**Issue by Demivdm** [DamianR2004/look-and-feel-corporate-identity#6]
Je mag een h1 maar 1 keer gebruiken. Gebruik de h1 voor de belangrijkste titel op de pagina. De rest van de header mogen h2,h3 ect worden.

https://github.com/DamianR2004/look-and-feel-corporate-identity/blob/702e3c6e2a4e619365b0a36dfff0717b60501400/index.html#L395

**Comment by DamianR2004** [comment]
is opgelost, thanks!
