### ISSUE TITLE
Verstuur button een input maken

### ISSUE THREAD

**Issue by CathelijneVisser** [DamianR2004/look-and-feel-corporate-identity#8]
https://github.com/DamianR2004/look-and-feel-corporate-identity/blob/6ba9ea5dcb7ab483955cd5f4f0a9d26fe5e67cb3/index.html#L414

Het is semantischer om van deze button een input te maken met als type="submit"

**Comment by DamianR2004** [comment]
Opgelost, thanks! 😄
